- name: swap off
  become: yes
  shell: '{{ item }}'
  with_items:
    - swapoff --all
    - systemctl stop dphys-swapfile
    - systemctl disable dphys-swapfile

# - name: docker install specific version 19.03.11 # https://docs.docker.com/engine/install/ubuntu/
#   apt:
#     name: '{{ item }}'
#     state: "present"
#     update_cache: yes
#     force: yes
#   with_items:
#     - docker-ce={{docker_version}}
#     - docker-ce-cli={{docker_version}}
#     - containerd.io
#   notify:
#     - docker status
# - name: add pi to docker group
#   user: name=pi append=yes groups=docker
#   become: true
- name: docker restarted
  service:
    name: docker
    state: restarted
    enabled: yes

# install kubeadm, kubelet, kubectl
# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

# - name: Configure node ip
#   lineinfile:
#     path: /etc/default/kubelet
#     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted