all:
  hosts:
    pi-master:
    pi-worker1:
    pi-worker2:
  children:
    cluster_nodes:
      hosts:
        pi-master:
        pi-worker1:
        pi-worker2:
    masters:
      hosts:
        pi-master:
    workers:
      hosts:
        pi-worker1:
        pi-worker2:
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/id_rsa