all:
  hosts:
    k8s-master:
    k8s-worker1:
    k8s-worker2:
  children:
    cluster_nodes:
      hosts:
        k8s-master:
        k8s-worker1:
        k8s-worker2:
    masters:
      hosts:
        k8smaster:
    workers:
      hosts:
        k8sworker1:
        k8sworker2:
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/id_rsa