---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
---
# deploymentの定義、ただのnginxの定義をしている
# apiVersion: apps/v1 #APIのバージョン
# kind: Deployment #リソースの種類
# metadata:
#   name: test-nginx #名前を付ける
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 0
#       maxSurge: 1
#   replicas: 4 #レプリカ数（Podの数）
#   selector: #どのPodを起動するか
#     matchLabels:
#       app: test-nginx #テンプレートを指定
#   template: #作成されるPodのテンプレート
#     metadata:
#       labels:
#         app: test-nginx #Labelを付ける
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.16
#         ports:
#         - containerPort: 80 #コンテナのポート番号

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 4
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
# service経由でnodeにきた外部からのリクエストを通す、ポートフォワードしている
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: NodePort
#   selector:
#     app: test-nginx
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30000

# nodeに直接リクエストするのではなく、lbを使ってリクエストを捌くようにする
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx-service
#             port:
#               number: 30000