---
# when: 0 or 1で実行かどうか制御
# install系
- hosts: cluster_nodes
  become: true
  roles:
    - { role: setup, when: 0 }
    - { role: k8s_prepare, when: 0 }
  vars:
    - homepath: /home/pi

# reactのindexをコピーしてraspiの/tmp/buildに配置する
- hosts: workers
  become: true
  roles:
    - {role: index_deploy, when: 1}
  vars:
    - homepath: /home/pi

# manifestファイルの転送
- hosts: masters
  become: true
  roles:
    - {role: k8s_deploy, when: 1}
  vars:
    - homepath: /home/pi
    # - apply: 1