---
# - hosts: cluster_nodes
#   become: true
#   roles:
#     - { role: setup }
#     - { role: k8s_prepare }
#   vars:
#     - homepath: /home/pi

- hosts: masters
  become: true
  roles:
    - {role: k8s_deploy}
  vars:
    - homepath: /home/pi