---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/build"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 4
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: conf
            mountPath: /etc/nginx/conf.d/
          - name: docroot
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
        - name: conf
          configMap:
            name: nginx-conf
        - name: docroot
          persistentVolumeClaim:
            claimName: task-pv-claim
---