---
# Volumeをマウントする領域の確保
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docroot
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/pi/build"
---
# Volumeを要求してあう領域を確保する
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docroot-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# NginxのconfigMapの作成
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen     80;
      server_tokens on;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
---
# Deploymentの定義
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 4
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: conf
            mountPath: /etc/nginx/conf.d/
          - name: docrootc
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
        - name: conf
          configMap:
            name: nginx-conf
        - name: docrootc
          persistentVolumeClaim:
            claimName: docroot-claim
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    run: my-nginx
---
# WIP
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ingress-system
# ---
# service経由でnodeにきた外部からのリクエストを通す、ポートフォワードしている
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: NodePort
#   selector:
#     app: test-nginx
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30000

# nodeに直接リクエストするのではなく、lbを使ってリクエストを捌くようにする
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: pi-master
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: my-nginx
#             port:
#               number: 80